Rcpp: RcppMatrix< T > Class Template Reference
RcppMatrix< T > Class Template Reference
#include <Rcpp.h>
Public Member Functions
RcppMatrix (SEXP mat)
RcppMatrix (int nx, int ny)
int getDim1 ()
int getDim2 ()
T & operator() (int i, int j)
T ** cMatrix ()
std::vector< std::vector< T > > stlMatrix ()
Private Attributes
int dim1
int dim2
T ** a
Detailed Description
template<typename T>
class RcppMatrix< T >
Definition at line 445 of file Rcpp.h.
Constructor & Destructor Documentation
template<typename T> RcppMatrix< T >::RcppMatrix (SEXP mat) [inline]
Definition at line 338 of file Rcpp.cpp.
References RcppMatrix< T >::a, RcppMatrix< T >::dim1, and RcppMatrix< T >::dim2.
template<typename T> RcppMatrix< T >::RcppMatrix (int nx, int ny) [inline]
Definition at line 369 of file Rcpp.cpp.
References RcppMatrix< T >::a, RcppMatrix< T >::dim1, and RcppMatrix< T >::dim2.
Member Function Documentation
template<typename T> int RcppMatrix< T >::getDim1 () [inline]
Definition at line 449 of file Rcpp.h.
References RcppMatrix< T >::dim1.
Referenced by RcppResultSet::add(), and Rcpp_Example().
template<typename T> int RcppMatrix< T >::getDim2 () [inline]
Definition at line 450 of file Rcpp.h.
References RcppMatrix< T >::dim2.
Referenced by RcppResultSet::add(), and Rcpp_Example().
template<typename T> T& RcppMatrix< T >::operator() (int i, int j) [inline]
Definition at line 451 of file Rcpp.h.
References RcppMatrix< T >::a, RcppMatrix< T >::dim1, and RcppMatrix< T >::dim2.
template<typename T> T ** RcppMatrix< T >::cMatrix () [inline]
Definition at line 396 of file Rcpp.cpp.
References RcppMatrix< T >::a, RcppMatrix< T >::dim1, and RcppMatrix< T >::dim2.
Referenced by RcppResultSet::add(), and Rcpp_Example().
template<typename T> std::vector< std::vector< T > > RcppMatrix< T >::stlMatrix () [inline]
Definition at line 383 of file Rcpp.cpp.
References RcppMatrix< T >::a, RcppMatrix< T >::dim1, and RcppMatrix< T >::dim2.
Referenced by Rcpp_Example().
Member Data Documentation
template<typename T> int RcppMatrix< T >::dim1 [private]
Definition at line 462 of file Rcpp.h.
Referenced by RcppMatrix< T >::cMatrix(), RcppMatrix< T >::getDim1(), RcppMatrix< T >::operator()(), RcppMatrix< T >::RcppMatrix(), and RcppMatrix< T >::stlMatrix().
template<typename T> int RcppMatrix< T >::dim2 [private]
Definition at line 462 of file Rcpp.h.
Referenced by RcppMatrix< T >::cMatrix(), RcppMatrix< T >::getDim2(), RcppMatrix< T >::operator()(), RcppMatrix< T >::RcppMatrix(), and RcppMatrix< T >::stlMatrix().
template<typename T> T** RcppMatrix< T >::a [private]
Definition at line 463 of file Rcpp.h.
Referenced by RcppMatrix< T >::cMatrix(), RcppMatrix< T >::operator()(), RcppMatrix< T >::RcppMatrix(), and RcppMatrix< T >::stlMatrix().
The documentation for this class was generated from the following files:
src/Rcpp.h
src/Rcpp.cpp