Rcpp: RcppSexp Class Reference
RcppSexp Class Reference
#include <RcppSexp.h>
Public Member Functions
RcppSexp (SEXP m_sexp=R_NilValue)
~RcppSexp ()
RcppSexp (const double &v)
RcppSexp (const int &v)
RcppSexp (const Rbyte &v)
RcppSexp (const std::string &v)
RcppSexp (const bool &v)
RcppSexp (const std::vector< int > &v)
RcppSexp (const std::vector< double > &v)
RcppSexp (const std::vector< std::string > &v)
RcppSexp (const std::vector< Rbyte > &v)
RcppSexp (const std::vector< bool > &v)
RcppSexp (const std::set< int > &v)
RcppSexp (const std::set< double > &v)
RcppSexp (const std::set< std::string > &v)
RcppSexp (const std::set< Rbyte > &v)
bool asBool () const
double asDouble () const
int asInt () const
Rbyte asRaw () const
std::string asStdString () const
std::vector< int > asStdVectorInt () const
std::vector< double > asStdVectorDouble () const
std::vector< std::string > asStdVectorString () const
std::vector< Rbyte > asStdVectorRaw () const
std::vector< bool > asStdVectorBool () const
void protect ()
void release ()
operator SEXP () const
std::vector< std::string > attributeNames () const
bool hasAttribute (const std::string &attr) const
SEXP attr (const std::string &name) const
bool isNULL () const
int sexp_type () const
SEXP asSexp () const
Protected Member Functions
void DEPRECATED ()
Protected Attributes
Rcpp::RObject object
Detailed Description
This class is DEPRECATED, will be DEFUNCT in a next version and eventually removed from Rcpp.
The alternative is to use the Rcpp::RObject class and the set of functions Rcpp::wrap.
Definition at line 35 of file RcppSexp.h.
Constructor & Destructor Documentation
RcppSexp::RcppSexp (SEXP m_sexp = R_NilValue) [inline]
wraps the SEXP into an Rcpp::RObject. The RObject does not automatically enforce protection of the SEXP, so if you want to preserve the SEXP from R garbage collection, you must call the protect member function
Definition at line 44 of file RcppSexp.h.
References DEPRECATED().
RcppSexp::~RcppSexp ()
RcppSexp::RcppSexp (const double & v) [inline]
Definition at line 50 of file RcppSexp.h.
References DEPRECATED().
RcppSexp::RcppSexp (const int & v) [inline]
Definition at line 51 of file RcppSexp.h.
References DEPRECATED().
RcppSexp::RcppSexp (const Rbyte & v) [inline]
Definition at line 52 of file RcppSexp.h.
References DEPRECATED().
RcppSexp::RcppSexp (const std::string & v) [inline]
Definition at line 53 of file RcppSexp.h.
References DEPRECATED().
RcppSexp::RcppSexp (const bool & v) [inline]
Definition at line 54 of file RcppSexp.h.
References DEPRECATED().
RcppSexp::RcppSexp (const std::vector< int > & v) [inline]
Definition at line 56 of file RcppSexp.h.
References DEPRECATED().
RcppSexp::RcppSexp (const std::vector< double > & v) [inline]
Definition at line 57 of file RcppSexp.h.
References DEPRECATED().
RcppSexp::RcppSexp (const std::vector< std::string > & v) [inline]
Definition at line 58 of file RcppSexp.h.
References DEPRECATED().
RcppSexp::RcppSexp (const std::vector< Rbyte > & v) [inline]
Definition at line 59 of file RcppSexp.h.
References DEPRECATED().
RcppSexp::RcppSexp (const std::vector< bool > & v) [inline]
Definition at line 60 of file RcppSexp.h.
References DEPRECATED().
RcppSexp::RcppSexp (const std::set< int > & v) [inline]
Definition at line 62 of file RcppSexp.h.
References DEPRECATED().
RcppSexp::RcppSexp (const std::set< double > & v) [inline]
Definition at line 63 of file RcppSexp.h.
References DEPRECATED().
RcppSexp::RcppSexp (const std::set< std::string > & v) [inline]
Definition at line 64 of file RcppSexp.h.
References DEPRECATED().
RcppSexp::RcppSexp (const std::set< Rbyte > & v) [inline]
Definition at line 65 of file RcppSexp.h.
References DEPRECATED().
Member Function Documentation
bool RcppSexp::asBool () const [inline]
Definition at line 70 of file RcppSexp.h.
double RcppSexp::asDouble () const [inline]
Definition at line 71 of file RcppSexp.h.
int RcppSexp::asInt () const [inline]
Definition at line 72 of file RcppSexp.h.
Rbyte RcppSexp::asRaw () const [inline]
Definition at line 73 of file RcppSexp.h.
SEXP RcppSexp::asSexp () const [inline]
explicit conversion to SEXP
Definition at line 130 of file RcppSexp.h.
std::string RcppSexp::asStdString () const [inline]
Definition at line 74 of file RcppSexp.h.
std::vector<bool> RcppSexp::asStdVectorBool () const [inline]
Definition at line 79 of file RcppSexp.h.
std::vector<double> RcppSexp::asStdVectorDouble () const [inline]
Definition at line 76 of file RcppSexp.h.
std::vector<int> RcppSexp::asStdVectorInt () const [inline]
Definition at line 75 of file RcppSexp.h.
std::vector<Rbyte> RcppSexp::asStdVectorRaw () const [inline]
Definition at line 78 of file RcppSexp.h.
std::vector<std::string> RcppSexp::asStdVectorString () const [inline]
Definition at line 77 of file RcppSexp.h.
SEXP RcppSexp::attr (const std::string & name) const [inline]
extract the given attribute
Definition at line 115 of file RcppSexp.h.
std::vector<std::string> RcppSexp::attributeNames () const [inline]
extracts the names of the attributes of the wrapped SEXP
Definition at line 105 of file RcppSexp.h.
void RcppSexp::DEPRECATED () [inline, protected]
Definition at line 139 of file RcppSexp.h.
Referenced by RcppSexp().
bool RcppSexp::hasAttribute (const std::string & attr) const [inline]
Identifies if the SEXP has the given attribute
Definition at line 110 of file RcppSexp.h.
bool RcppSexp::isNULL () const [inline]
is this object NULL
Definition at line 120 of file RcppSexp.h.
RcppSexp::operator SEXP () const [inline]
implicit conversion to SEXP
Definition at line 97 of file RcppSexp.h.
void RcppSexp::protect () [inline]
Calls the preserve method of the wrapped RObject, which prevents the underlying SEXP from being garbage collected
Definition at line 86 of file RcppSexp.h.
void RcppSexp::release () [inline]
calls the release method of the RObject. the underlying SEXP becomes subject of garbage collection
Definition at line 92 of file RcppSexp.h.
int RcppSexp::sexp_type () const [inline]
The SEXP typeof, calls TYPEOF on the underlying SEXP
Definition at line 125 of file RcppSexp.h.
Member Data Documentation
Rcpp::RObject RcppSexp::object [protected]
The RObject this wraps
Definition at line 137 of file RcppSexp.h.
The documentation for this class was generated from the following file:
src/RcppSexp.h