Rcpp: RcppDate Class Reference
RcppDate Class Reference
#include <Rcpp.h>
Public Member Functions
RcppDate ()
RcppDate (int Rjdn)
RcppDate (int month_, int day_, int year_)
int getMonth () const
int getDay () const
int getYear () const
int getJDN () const
Static Public Attributes
static const int Jan1970Offset = 2440588
static const int QLtoJan1970Offset = 25569
Private Member Functions
void mdy2jdn ()
void jdn2mdy ()
Private Attributes
int month
int day
int year
int jdn
Friends
RcppDate operator+ (const RcppDate &date, int offset)
int operator- (const RcppDate &date1, const RcppDate &date2)
bool operator< (const RcppDate &date1, const RcppDate &date2)
bool operator> (const RcppDate &date1, const RcppDate &date2)
bool operator== (const RcppDate &date1, const RcppDate &date2)
bool operator>= (const RcppDate &date1, const RcppDate &date2)
bool operator<= (const RcppDate &date1, const RcppDate &date2)
std::ostream & operator<< (std::ostream &os, const RcppDate &date)
Detailed Description
Definition at line 47 of file Rcpp.h.
Constructor & Destructor Documentation
RcppDate::RcppDate () [inline]
Definition at line 57 of file Rcpp.h.
References day, mdy2jdn(), month, and year.
RcppDate::RcppDate (int Rjdn) [inline]
Definition at line 58 of file Rcpp.h.
References Jan1970Offset, jdn, and jdn2mdy().
RcppDate::RcppDate (int month_, int day_, int year_) [inline]
Definition at line 59 of file Rcpp.h.
References mdy2jdn().
Member Function Documentation
int RcppDate::getDay () const [inline]
Definition at line 67 of file Rcpp.h.
References day.
Referenced by operator<<(), Rcpp_Example(), and RcppParamsExample().
int RcppDate::getJDN () const [inline]
Definition at line 69 of file Rcpp.h.
References jdn.
Referenced by RcppResultSet::add(), RcppFunction::appendToRList(), and ColDatum::getDateRCode().
int RcppDate::getMonth () const [inline]
Definition at line 66 of file Rcpp.h.
References month.
Referenced by operator<<(), Rcpp_Example(), and RcppParamsExample().
int RcppDate::getYear () const [inline]
Definition at line 68 of file Rcpp.h.
References year.
Referenced by operator<<(), Rcpp_Example(), and RcppParamsExample().
void RcppDate::jdn2mdy () [private]
Definition at line 865 of file Rcpp.cpp.
References day, jdn, month, and year.
Referenced by operator+(), and RcppDate().
void RcppDate::mdy2jdn () [private]
Definition at line 855 of file Rcpp.cpp.
References day, jdn, month, and year.
Referenced by RcppDate().
Friends And Related Function Documentation
RcppDate operator+ (const RcppDate & date, int offset) [friend]
Definition at line 805 of file Rcpp.cpp.
int operator- (const RcppDate & date1, const RcppDate & date2) [friend]
Definition at line 812 of file Rcpp.cpp.
bool operator< (const RcppDate & date1, const RcppDate & date2) [friend]
Definition at line 816 of file Rcpp.cpp.
std::ostream& operator<< (std::ostream & os, const RcppDate & date) [friend]
Definition at line 799 of file Rcpp.cpp.
bool operator<= (const RcppDate & date1, const RcppDate & date2) [friend]
Definition at line 828 of file Rcpp.cpp.
bool operator== (const RcppDate & date1, const RcppDate & date2) [friend]
Definition at line 832 of file Rcpp.cpp.
bool operator> (const RcppDate & date1, const RcppDate & date2) [friend]
Definition at line 820 of file Rcpp.cpp.
bool operator>= (const RcppDate & date1, const RcppDate & date2) [friend]
Definition at line 824 of file Rcpp.cpp.
Member Data Documentation
int RcppDate::day [private]
Definition at line 51 of file Rcpp.h.
Referenced by getDay(), jdn2mdy(), mdy2jdn(), operator+(), and RcppDate().
const int RcppDate::Jan1970Offset = 2440588 [static]
Definition at line 55 of file Rcpp.h.
Referenced by RcppResultSet::add(), RcppFunction::appendToRList(), ColDatum::getDateRCode(), and RcppDate().
int RcppDate::jdn [private]
Definition at line 52 of file Rcpp.h.
Referenced by getJDN(), jdn2mdy(), mdy2jdn(), operator+(), operator-(), operator<(), operator<=(), operator==(), operator>(), operator>=(), and RcppDate().
int RcppDate::month [private]
Definition at line 51 of file Rcpp.h.
Referenced by getMonth(), jdn2mdy(), mdy2jdn(), operator+(), and RcppDate().
const int RcppDate::QLtoJan1970Offset = 25569 [static]
Definition at line 56 of file Rcpp.h.
int RcppDate::year [private]
Definition at line 51 of file Rcpp.h.
Referenced by getYear(), jdn2mdy(), mdy2jdn(), operator+(), and RcppDate().
The documentation for this class was generated from the following files:
src/Rcpp.h
src/Rcpp.cpp