Rcpp: RcppVector< T > Class Template Reference
RcppVector< T > Class Template Reference
#include <Rcpp.h>
Public Member Functions
RcppVector (SEXP vec)
RcppVector (int len)
int size ()
T & operator() (int i)
T * cVector ()
std::vector< T > stlVector ()
Private Attributes
int len
T * v
Detailed Description
template<typename T>
class RcppVector< T >
Definition at line 360 of file Rcpp.h.
Constructor & Destructor Documentation
template<typename T > RcppVector< T >::RcppVector (SEXP vec) [inline]
Definition at line 299 of file Rcpp.cpp.
References RcppVector< T >::len, and RcppVector< T >::v.
template<typename T > RcppVector< T >::RcppVector (int len) [inline]
Definition at line 323 of file Rcpp.cpp.
References RcppVector< T >::len, and RcppVector< T >::v.
Member Function Documentation
template<typename T > T * RcppVector< T >::cVector () [inline]
Definition at line 331 of file Rcpp.cpp.
References RcppVector< T >::len, and RcppVector< T >::v.
Referenced by RcppResultSet::add(), and Rcpp_Example().
template<typename T> T& RcppVector< T >::operator() (int i) [inline]
Definition at line 365 of file Rcpp.h.
References RcppVector< T >::v.
template<typename T> int RcppVector< T >::size () [inline]
Definition at line 364 of file Rcpp.h.
Referenced by RcppResultSet::add(), Rcpp_Example(), and RcppVectorExample().
template<typename T > std::vector< T > RcppVector< T >::stlVector () [inline]
Definition at line 339 of file Rcpp.cpp.
References RcppVector< T >::len, and RcppVector< T >::v.
Referenced by Rcpp_Example().
Member Data Documentation
template<typename T> int RcppVector< T >::len [private]
Definition at line 376 of file Rcpp.h.
Referenced by RcppVector< T >::cVector(), RcppVector< T >::RcppVector(), and RcppVector< T >::stlVector().
template<typename T> T* RcppVector< T >::v [private]
Definition at line 377 of file Rcpp.h.
Referenced by RcppVector< T >::cVector(), RcppVector< T >::operator()(), RcppVector< T >::RcppVector(), and RcppVector< T >::stlVector().
The documentation for this class was generated from the following files:
src/Rcpp.h
src/Rcpp.cpp