Rcpp: RcppParams Class Reference
RcppParams Class Reference
#include <Rcpp.h>
Public Member Functions
RcppParams (SEXP params)
void checkNames (char *inputNames[], int len)
bool exists (std::string name)
double getDoubleValue (std::string name)
int getIntValue (std::string name)
std::string getStringValue (std::string name)
bool getBoolValue (std::string name)
RcppDate getDateValue (std::string name)
RcppDatetime getDatetimeValue (std::string name)
Private Attributes
std::map< std::string, int > pmap
SEXP _params
Detailed Description
Definition at line 151 of file Rcpp.h.
Constructor & Destructor Documentation
RcppParams::RcppParams (SEXP params)
Definition at line 24 of file Rcpp.cpp.
References _params, and pmap.
Member Function Documentation
void RcppParams::checkNames (char * inputNames[], int len)
Definition at line 40 of file Rcpp.cpp.
References pmap.
bool RcppParams::exists (std::string name)
Definition at line 50 of file Rcpp.cpp.
References pmap.
bool RcppParams::getBoolValue (std::string name)
Definition at line 178 of file Rcpp.cpp.
References _params, and pmap.
RcppDatetime RcppParams::getDatetimeValue (std::string name)
Definition at line 235 of file Rcpp.cpp.
References _params, and pmap.
RcppDate RcppParams::getDateValue (std::string name)
Definition at line 212 of file Rcpp.cpp.
References _params, and pmap.
Referenced by Rcpp_Example(), and RcppParamsExample().
double RcppParams::getDoubleValue (std::string name)
Definition at line 132 of file Rcpp.cpp.
References _params, and pmap.
Referenced by Rcpp_Example(), and RcppParamsExample().
int RcppParams::getIntValue (std::string name)
Definition at line 155 of file Rcpp.cpp.
References _params, and pmap.
Referenced by Rcpp_Example(), and RcppParamsExample().
std::string RcppParams::getStringValue (std::string name)
Definition at line 195 of file Rcpp.cpp.
References _params, and pmap.
Referenced by Rcpp_Example(), and RcppParamsExample().
Member Data Documentation
SEXP RcppParams::_params [private]
Definition at line 164 of file Rcpp.h.
Referenced by getBoolValue(), getDatetimeValue(), getDateValue(), getDoubleValue(), getIntValue(), getStringValue(), and RcppParams().
std::map<std::string, int> RcppParams::pmap [private]
Definition at line 163 of file Rcpp.h.
Referenced by checkNames(), exists(), getBoolValue(), getDatetimeValue(), getDateValue(), getDoubleValue(), getIntValue(), getStringValue(), and RcppParams().
The documentation for this class was generated from the following files:
src/Rcpp.h
src/Rcpp.cpp