Rcpp: RcppResultSet Class Reference
RcppResultSet Class Reference
#include <RcppResultSet.h>
Public Member Functions
RcppResultSet ()
void add (std::string, double)
void add (std::string, int)
void add (std::string, std::string)
void add (std::string, double *, int)
void add (std::string, int *, int)
void add (std::string, double **, int, int)
void add (std::string, int **, int, int)
void add (std::string, RcppDate &)
void add (std::string, RcppDateVector &)
void add (std::string, RcppDatetime &)
void add (std::string, RcppDatetimeVector &)
void add (std::string, RcppStringVector &)
void add (std::string, std::vector< double > &)
void add (std::string, std::vector< int > &)
void add (std::string, std::vector< std::vector< double > > &)
void add (std::string, std::vector< std::vector< int > > &)
void add (std::string, std::vector< std::string > &)
void add (std::string, RcppVector< int > &)
void add (std::string, RcppVector< double > &)
void add (std::string, RcppMatrix< int > &)
void add (std::string, RcppMatrix< double > &)
void add (std::string, RcppFrame &)
void add (std::string, RcppList &)
void add (std::string, SEXP, bool isProtected)
SEXP getReturnList ()
SEXP getSEXP ()
Protected Attributes
int numProtected
std::list< std::pair
< std::string, SEXP > > values
Detailed Description
Definition at line 40 of file RcppResultSet.h.
Constructor & Destructor Documentation
RcppResultSet::RcppResultSet ()
Definition at line 25 of file RcppResultSet.cpp.
Member Function Documentation
void RcppResultSet::add (std::string name, SEXP sexp, bool isProtected)
Definition at line 343 of file RcppResultSet.cpp.
References numProtected, and values.
void RcppResultSet::add (std::string name, RcppList & list)
Definition at line 338 of file RcppResultSet.cpp.
References RcppList::getList(), and values.
void RcppResultSet::add (std::string name, RcppFrame & frame)
Definition at line 256 of file RcppResultSet.cpp.
References COLTYPE_DATE, COLTYPE_DATETIME, COLTYPE_DOUBLE, COLTYPE_FACTOR, COLTYPE_INT, COLTYPE_LOGICAL, COLTYPE_STRING, RcppFrame::getColNames(), RcppFrame::getTableData(), numProtected, and values.
void RcppResultSet::add (std::string name, RcppMatrix< double > & mat)
Definition at line 244 of file RcppResultSet.cpp.
References RcppMatrix< T >::cMatrix(), RcppMatrix< T >::getDim1(), RcppMatrix< T >::getDim2(), numProtected, and values.
void RcppResultSet::add (std::string name, RcppMatrix< int > & mat)
Definition at line 232 of file RcppResultSet.cpp.
References RcppMatrix< T >::cMatrix(), RcppMatrix< T >::getDim1(), RcppMatrix< T >::getDim2(), numProtected, and values.
void RcppResultSet::add (std::string name, RcppVector< double > & vec)
Definition at line 222 of file RcppResultSet.cpp.
References RcppVector< T >::cVector(), numProtected, RcppVector< T >::size(), and values.
void RcppResultSet::add (std::string name, RcppVector< int > & vec)
Definition at line 212 of file RcppResultSet.cpp.
References RcppVector< T >::cVector(), numProtected, RcppVector< T >::size(), and values.
void RcppResultSet::add (std::string name, std::vector< std::string > & vec)
Definition at line 149 of file RcppResultSet.cpp.
References numProtected, and values.
void RcppResultSet::add (std::string name, std::vector< std::vector< int > > & mat)
Definition at line 182 of file RcppResultSet.cpp.
References numProtected, and values.
void RcppResultSet::add (std::string name, std::vector< std::vector< double > > & mat)
Definition at line 197 of file RcppResultSet.cpp.
References numProtected, and values.
void RcppResultSet::add (std::string name, std::vector< int > & vec)
Definition at line 160 of file RcppResultSet.cpp.
References numProtected, and values.
void RcppResultSet::add (std::string name, std::vector< double > & vec)
Definition at line 171 of file RcppResultSet.cpp.
References numProtected, and values.
void RcppResultSet::add (std::string name, RcppStringVector & stringvec)
Definition at line 108 of file RcppResultSet.cpp.
References numProtected, RcppStringVector::size(), and values.
void RcppResultSet::add (std::string name, RcppDatetimeVector & dtvec)
Definition at line 94 of file RcppResultSet.cpp.
References numProtected, RcppDatetimeVector::size(), and values.
void RcppResultSet::add (std::string name, RcppDatetime & datetime)
Definition at line 38 of file RcppResultSet.cpp.
References RcppDatetime::getFractionalTimestamp(), numProtected, and values.
void RcppResultSet::add (std::string name, RcppDateVector & datevec)
Definition at line 81 of file RcppResultSet.cpp.
References RcppDate::Jan1970Offset, numProtected, RcppDateVector::size(), and values.
void RcppResultSet::add (std::string name, RcppDate & date)
Definition at line 27 of file RcppResultSet.cpp.
References RcppDate::getJDN(), RcppDate::Jan1970Offset, numProtected, and values.
void RcppResultSet::add (std::string name, int ** mat, int nx, int ny)
Definition at line 138 of file RcppResultSet.cpp.
References numProtected, and values.
void RcppResultSet::add (std::string name, double ** mat, int nx, int ny)
Definition at line 127 of file RcppResultSet.cpp.
References numProtected, and values.
void RcppResultSet::add (std::string name, int * vec, int len)
Definition at line 117 of file RcppResultSet.cpp.
References numProtected, and values.
void RcppResultSet::add (std::string name, double * vec, int len)
Definition at line 71 of file RcppResultSet.cpp.
References numProtected, and values.
void RcppResultSet::add (std::string name, std::string strvalue)
Definition at line 64 of file RcppResultSet.cpp.
References numProtected, and values.
void RcppResultSet::add (std::string name, int i)
Definition at line 57 of file RcppResultSet.cpp.
References numProtected, and values.
void RcppResultSet::add (std::string name, double x)
Definition at line 50 of file RcppResultSet.cpp.
References numProtected, and values.
Referenced by Rcpp_Example(), RcppDateExample(), and RcppVectorExample().
SEXP RcppResultSet::getReturnList ()
Definition at line 349 of file RcppResultSet.cpp.
References numProtected, and values.
Referenced by Rcpp_Example(), RcppDateExample(), and RcppVectorExample().
SEXP RcppResultSet::getSEXP ()
Definition at line 363 of file RcppResultSet.cpp.
References numProtected, and values.
Member Data Documentation
int RcppResultSet::numProtected [protected]
Definition at line 70 of file RcppResultSet.h.
Referenced by add(), getReturnList(), and getSEXP().
std::list<std::pair<std::string,SEXP> > RcppResultSet::values [protected]
Definition at line 71 of file RcppResultSet.h.
Referenced by add(), getReturnList(), and getSEXP().
The documentation for this class was generated from the following files:
src/RcppResultSet.h
src/RcppResultSet.cpp