Rcpp: MyRVectorFunc Class Reference
MyRVectorFunc Class Reference
Inherits RcppFunction.
Public Member Functions
MyRVectorFunc (SEXP fn)
double getSum (std::vector< double > &v)
Detailed Description
Definition at line 36 of file RcppExample.cpp.
Constructor & Destructor Documentation
MyRVectorFunc::MyRVectorFunc (SEXP fn) [inline]
Definition at line 38 of file RcppExample.cpp.
Member Function Documentation
double MyRVectorFunc::getSum (std::vector< double > & v) [inline]
Definition at line 42 of file RcppExample.cpp.
References RcppFunction::clearProtectionStack(), RcppFunction::setRVector(), and RcppFunction::vectorCall().
Referenced by Rcpp_Example().
The documentation for this class was generated from the following file:
src/RcppExample.cpp