Rcpp: RcppDatetime Class Reference
RcppDatetime Class Reference
#include <Rcpp.h>
Public Member Functions
RcppDatetime (void)
RcppDatetime (const double d)
double getFractionalTimestamp (void) const
int getYear (void)
int getMonth (void)
int getDay (void)
int getWeekday (void)
int getHour (void)
int getMinute (void)
int getSecond (void)
int getMicroSec (void)
Private Member Functions
void parseTime ()
Private Attributes
double m_d
bool m_parsed
int m_us
struct tm m_tm
Friends
class ColDatum
RcppDatetime operator+ (const RcppDatetime &date, double offset)
double operator- (const RcppDatetime &dt1, const RcppDatetime &dt2)
bool operator< (const RcppDatetime &dt1, const RcppDatetime &dt2)
bool operator<= (const RcppDatetime &dt1, const RcppDatetime &dt2)
bool operator> (const RcppDatetime &dt1, const RcppDatetime &dt2)
bool operator>= (const RcppDatetime &dt1, const RcppDatetime &dt2)
bool operator== (const RcppDatetime &dt1, const RcppDatetime &dt2)
std::ostream & operator<< (std::ostream &os, const RcppDatetime &datetime)
Detailed Description
Definition at line 90 of file Rcpp.h.
Constructor & Destructor Documentation
RcppDatetime::RcppDatetime (void) [inline]
Definition at line 111 of file Rcpp.h.
RcppDatetime::RcppDatetime (const double d) [inline]
Definition at line 112 of file Rcpp.h.
Member Function Documentation
int RcppDatetime::getDay (void) [inline]
Definition at line 118 of file Rcpp.h.
References m_parsed, m_tm, and parseTime().
double RcppDatetime::getFractionalTimestamp (void) const [inline]
Definition at line 114 of file Rcpp.h.
References m_d.
Referenced by RcppResultSet::add(), and RcppFunction::appendToRList().
int RcppDatetime::getHour (void) [inline]
Definition at line 120 of file Rcpp.h.
References m_parsed, m_tm, and parseTime().
int RcppDatetime::getMicroSec (void) [inline]
Definition at line 123 of file Rcpp.h.
References m_parsed, m_us, and parseTime().
int RcppDatetime::getMinute (void) [inline]
Definition at line 121 of file Rcpp.h.
References m_parsed, m_tm, and parseTime().
int RcppDatetime::getMonth (void) [inline]
Definition at line 117 of file Rcpp.h.
References m_parsed, m_tm, and parseTime().
int RcppDatetime::getSecond (void) [inline]
Definition at line 122 of file Rcpp.h.
References m_parsed, m_tm, and parseTime().
int RcppDatetime::getWeekday (void) [inline]
Definition at line 119 of file Rcpp.h.
References m_parsed, m_tm, and parseTime().
int RcppDatetime::getYear (void) [inline]
Definition at line 116 of file Rcpp.h.
References m_parsed, m_tm, and parseTime().
void RcppDatetime::parseTime () [inline, private]
Definition at line 96 of file Rcpp.h.
References m_d, m_parsed, m_tm, and m_us.
Referenced by getDay(), getHour(), getMicroSec(), getMinute(), getMonth(), getSecond(), getWeekday(), and getYear().
Friends And Related Function Documentation
friend class ColDatum [friend]
Definition at line 103 of file Rcpp.h.
RcppDatetime operator+ (const RcppDatetime & date, double offset) [friend]
Definition at line 125 of file Rcpp.h.
double operator- (const RcppDatetime & dt1, const RcppDatetime & dt2) [friend]
Definition at line 131 of file Rcpp.h.
bool operator< (const RcppDatetime & dt1, const RcppDatetime & dt2) [friend]
Definition at line 132 of file Rcpp.h.
std::ostream& operator<< (std::ostream & os, const RcppDatetime & datetime) [friend]
Definition at line 138 of file Rcpp.h.
bool operator<= (const RcppDatetime & dt1, const RcppDatetime & dt2) [friend]
Definition at line 133 of file Rcpp.h.
bool operator== (const RcppDatetime & dt1, const RcppDatetime & dt2) [friend]
Definition at line 136 of file Rcpp.h.
bool operator> (const RcppDatetime & dt1, const RcppDatetime & dt2) [friend]
Definition at line 134 of file Rcpp.h.
bool operator>= (const RcppDatetime & dt1, const RcppDatetime & dt2) [friend]
Definition at line 135 of file Rcpp.h.
Member Data Documentation
double RcppDatetime::m_d [private]
Definition at line 92 of file Rcpp.h.
Referenced by getFractionalTimestamp(), parseTime(), and ColDatum::setDatetimeValue().
bool RcppDatetime::m_parsed [private]
Definition at line 93 of file Rcpp.h.
Referenced by getDay(), getHour(), getMicroSec(), getMinute(), getMonth(), getSecond(), getWeekday(), getYear(), and parseTime().
struct tm RcppDatetime::m_tm [read, private]
Definition at line 95 of file Rcpp.h.
Referenced by getDay(), getHour(), getMinute(), getMonth(), getSecond(), getWeekday(), getYear(), and parseTime().
int RcppDatetime::m_us [private]
Definition at line 94 of file Rcpp.h.
Referenced by getMicroSec(), and parseTime().
The documentation for this class was generated from the following file:
src/Rcpp.h