Rcpp: MyRListFunc Class Reference
MyRListFunc Class Reference
Inherits RcppFunction.
Public Member Functions
MyRListFunc (SEXP fn)
std::vector< double > addOne (double alpha, double beta, double gamma)
Detailed Description
Definition at line 78 of file RcppExample.cpp.
Constructor & Destructor Documentation
MyRListFunc::MyRListFunc (SEXP fn) [inline]
Definition at line 80 of file RcppExample.cpp.
Member Function Documentation
std::vector<double> MyRListFunc::addOne (double alpha, double beta, double gamma) [inline]
Definition at line 81 of file RcppExample.cpp.
References RcppFunction::appendToRList(), RcppFunction::clearProtectionStack(), RcppFunction::listCall(), and RcppFunction::setRListSize().
Referenced by Rcpp_Example().
The documentation for this class was generated from the following file:
src/RcppExample.cpp