Rcpp: src/RcppCommon.cpp File Reference
src/RcppCommon.cpp File Reference
#include <Rcpp.h>
#include <cstring>
Functions
char * copyMessageToR (const char *const mesg)
void logTxtFunction (const char *file, const int line, const char *expression)
Function Documentation
char* copyMessageToR (const char *const mesg)
Definition at line 29 of file RcppCommon.cpp.
Referenced by Rcpp_Example(), RcppDateExample(), RcppParamsExample(), and RcppVectorExample().
void logTxtFunction (const char * file, const int line, const char * expression) [inline]
Definition at line 39 of file RcppCommon.cpp.