Rcpp: src/RcppDate.cpp File Reference
src/RcppDate.cpp File Reference
#include <RcppDate.h>
Functions
std::ostream & operator<< (std::ostream &os, const RcppDate &date)
RcppDate operator+ (const RcppDate &date, int offset)
int operator- (const RcppDate &date2, const RcppDate &date1)
bool operator< (const RcppDate &date1, const RcppDate &date2)
bool operator> (const RcppDate &date1, const RcppDate &date2)
bool operator>= (const RcppDate &date1, const RcppDate &date2)
bool operator<= (const RcppDate &date1, const RcppDate &date2)
bool operator== (const RcppDate &date1, const RcppDate &date2)
Function Documentation
RcppDate operator+ (const RcppDate & date, int offset)
Definition at line 54 of file RcppDate.cpp.
References RcppDate::day, RcppDate::jdn, RcppDate::jdn2mdy(), RcppDate::month, and RcppDate::year.
int operator- (const RcppDate & date2, const RcppDate & date1)
Definition at line 61 of file RcppDate.cpp.
References RcppDate::jdn.
bool operator< (const RcppDate & date1, const RcppDate & date2)
Definition at line 65 of file RcppDate.cpp.
References RcppDate::jdn.
std::ostream& operator<< (std::ostream & os, const RcppDate & date)
Definition at line 48 of file RcppDate.cpp.
References RcppDate::getDay(), RcppDate::getMonth(), and RcppDate::getYear().
bool operator<= (const RcppDate & date1, const RcppDate & date2)
Definition at line 77 of file RcppDate.cpp.
References RcppDate::jdn.
bool operator== (const RcppDate & date1, const RcppDate & date2)
Definition at line 81 of file RcppDate.cpp.
References RcppDate::jdn.
bool operator> (const RcppDate & date1, const RcppDate & date2)
Definition at line 69 of file RcppDate.cpp.
References RcppDate::jdn.
bool operator>= (const RcppDate & date1, const RcppDate & date2)
Definition at line 73 of file RcppDate.cpp.
References RcppDate::jdn.