Rcpp: src/RcppCommon.h File Reference
src/RcppCommon.h File Reference
#include <exception>
#include <iostream>
#include <sstream>
#include <string>
#include <list>
#include <map>
#include <stdexcept>
#include <vector>
#include <R.h>
#include <Rinternals.h>
#include <R_ext/Callbacks.h>
#include <Rversion.h>
Defines
#define R_NO_REMAP
#define RcppExport extern "C"
#define logTxt(x)
Functions
char * copyMessageToR (const char *const mesg)
void logTxtFunction (const char *file, const int line, const char *expression)
void forward_uncaught_exceptions_to_r ()
RcppExport SEXP initUncaughtExceptionHandler ()
Define Documentation
#define logTxt (x)
Definition at line 56 of file RcppCommon.h.
Referenced by Rcpp::wrap().
#define R_NO_REMAP
Definition at line 37 of file RcppCommon.h.
#define RcppExport extern "C"
Definition at line 47 of file RcppCommon.h.
Function Documentation
char* copyMessageToR (const char *const mesg)
Definition at line 29 of file RcppCommon.cpp.
Referenced by Rcpp_Example(), RcppDateExample(), RcppParamsExample(), and RcppVectorExample().
void forward_uncaught_exceptions_to_r ()
Definition at line 29 of file exceptions.cpp.
Referenced by initUncaughtExceptionHandler().
RcppExport SEXP initUncaughtExceptionHandler ()
Definition at line 77 of file exceptions.cpp.
References forward_uncaught_exceptions_to_r().
void logTxtFunction (const char * file, const int line, const char * expression) [inline]
Definition at line 39 of file RcppCommon.cpp.