Rcpp: src/RcppExample.cpp File Reference
src/RcppExample.cpp File Reference
#include <Rcpp.h>
Classes
class MyRVectorFunc
class MyRListFunc
Functions
RcppExport SEXP Rcpp_Example (SEXP params, SEXP nlist, SEXP numvec, SEXP nummat, SEXP df, SEXP datevec, SEXP stringvec, SEXP fnvec, SEXP fnlist)
RcppExport SEXP RcppParamsExample (SEXP params)
RcppExport SEXP RcppDateExample (SEXP dvsexp, SEXP dtvsexp)
RcppExport SEXP RcppVectorExample (SEXP vector)
RcppExport SEXP RcppXPtrExample_create_external_pointer ()
RcppExport SEXP RcppXPtrExample_get_external_pointer (SEXP x)
Function Documentation
RcppExport SEXP Rcpp_Example (SEXP params, SEXP nlist, SEXP numvec, SEXP nummat, SEXP df, SEXP datevec, SEXP stringvec, SEXP fnvec, SEXP fnlist)
Definition at line 110 of file RcppExample.cpp.
References RcppResultSet::add(), MyRListFunc::addOne(), RcppFrame::addRow(), RcppMatrix< T >::cMatrix(), copyMessageToR(), RcppVector< T >::cVector(), RcppParams::getDateValue(), RcppDate::getDay(), RcppMatrix< T >::getDim1(), RcppMatrix< T >::getDim2(), RcppParams::getDoubleValue(), RcppParams::getIntValue(), RcppDate::getMonth(), RcppNumList::getName(), RcppResultSet::getReturnList(), RcppParams::getStringValue(), MyRVectorFunc::getSum(), RcppNumList::getValue(), RcppDate::getYear(), RcppVector< T >::size(), RcppMatrix< T >::stlMatrix(), and RcppVector< T >::stlVector().
RcppExport SEXP RcppDateExample (SEXP dvsexp, SEXP dtvsexp)
Definition at line 383 of file RcppExample.cpp.
References RcppResultSet::add(), copyMessageToR(), RcppResultSet::getReturnList(), RcppDatetimeVector::size(), and RcppDateVector::size().
RcppExport SEXP RcppParamsExample (SEXP params)
Definition at line 334 of file RcppExample.cpp.
References copyMessageToR(), RcppParams::getDateValue(), RcppDate::getDay(), RcppParams::getDoubleValue(), RcppParams::getIntValue(), RcppDate::getMonth(), RcppParams::getStringValue(), and RcppDate::getYear().
RcppExport SEXP RcppVectorExample (SEXP vector)
Definition at line 424 of file RcppExample.cpp.
References RcppResultSet::add(), copyMessageToR(), RcppResultSet::getReturnList(), and RcppVector< T >::size().
RcppExport SEXP RcppXPtrExample_create_external_pointer ()
Definition at line 465 of file RcppExample.cpp.
RcppExport SEXP RcppXPtrExample_get_external_pointer (SEXP x)
Definition at line 473 of file RcppExample.cpp.