Rcpp: src/Rcpp.h File Reference
src/Rcpp.h File Reference
#include <iostream>
#include <sstream>
#include <string>
#include <list>
#include <map>
#include <stdexcept>
#include <vector>
#include <R.h>
#include <Rinternals.h>
#include <RcppList.h>
Classes
class RcppDate
class RcppDatetime
class RcppParams
class ColDatum
class RcppFrame
class RcppNumList
class RcppVector< T >
class RcppStringVector
class RcppDateVector
class RcppDatetimeVector
class RcppMatrix< T >
class RcppVectorView< T >
class RcppMatrixView< T >
class RcppStringVectorView
class RcppFunction
class RcppResultSet
Defines
#define R_NO_REMAP
#define RcppExport extern "C"
Enumerations
enum ColType {
COLTYPE_DOUBLE, COLTYPE_INT, COLTYPE_STRING, COLTYPE_FACTOR,
COLTYPE_LOGICAL, COLTYPE_DATE, COLTYPE_DATETIME
}
Functions
char * copyMessageToR (const char *const mesg)
Define Documentation
#define R_NO_REMAP
Definition at line 34 of file Rcpp.h.
#define RcppExport extern "C"
Definition at line 44 of file Rcpp.h.
Enumeration Type Documentation
enum ColType
Enumerator:
COLTYPE_DOUBLE
COLTYPE_INT
COLTYPE_STRING
COLTYPE_FACTOR
COLTYPE_LOGICAL
COLTYPE_DATE
COLTYPE_DATETIME
Definition at line 168 of file Rcpp.h.
Function Documentation
char* copyMessageToR (const char *const mesg)
Definition at line 1000 of file Rcpp.cpp.
Referenced by Rcpp_Example(), RcppDateExample(), RcppParamsExample(), and RcppVectorExample().