Rcpp: src/Rcpp.cpp File Reference
src/Rcpp.cpp File Reference
#include "Rcpp.h"
#include <cstring>
Functions
std::ostream & operator<< (std::ostream &os, const RcppDate &date)
RcppDate operator+ (const RcppDate &date, int offset)
int operator- (const RcppDate &date2, const RcppDate &date1)
bool operator< (const RcppDate &date1, const RcppDate &date2)
bool operator> (const RcppDate &date1, const RcppDate &date2)
bool operator>= (const RcppDate &date1, const RcppDate &date2)
bool operator<= (const RcppDate &date1, const RcppDate &date2)
bool operator== (const RcppDate &date1, const RcppDate &date2)
char * copyMessageToR (const char *const mesg)
Function Documentation
char* copyMessageToR (const char *const mesg)
Definition at line 1000 of file Rcpp.cpp.
Referenced by Rcpp_Example(), RcppDateExample(), RcppParamsExample(), and RcppVectorExample().
RcppDate operator+ (const RcppDate & date, int offset)
Definition at line 810 of file Rcpp.cpp.
References RcppDate::day, RcppDate::jdn, RcppDate::jdn2mdy(), RcppDate::month, and RcppDate::year.
int operator- (const RcppDate & date2, const RcppDate & date1)
Definition at line 817 of file Rcpp.cpp.
References RcppDate::jdn.
bool operator< (const RcppDate & date1, const RcppDate & date2)
Definition at line 821 of file Rcpp.cpp.
References RcppDate::jdn.
std::ostream& operator<< (std::ostream & os, const RcppDate & date)
Definition at line 804 of file Rcpp.cpp.
References RcppDate::getDay(), RcppDate::getMonth(), and RcppDate::getYear().
bool operator<= (const RcppDate & date1, const RcppDate & date2)
Definition at line 833 of file Rcpp.cpp.
References RcppDate::jdn.
bool operator== (const RcppDate & date1, const RcppDate & date2)
Definition at line 837 of file Rcpp.cpp.
References RcppDate::jdn.
bool operator> (const RcppDate & date1, const RcppDate & date2)
Definition at line 825 of file Rcpp.cpp.
References RcppDate::jdn.
bool operator>= (const RcppDate & date1, const RcppDate & date2)
Definition at line 829 of file Rcpp.cpp.
References RcppDate::jdn.