.TH "src/Environment.cpp" 3 "2 Jan 2010" "Rcpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Environment.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Rcpp/Environment.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBRcpp::safeAssign_s\fP"
.br
.ti -1c
.RI "struct \fBRcpp::safeFindNamespace_s\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBRcpp\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBRcpp::safeAssign\fP (void *data)"
.br
.ti -1c
.RI "static void \fBRcpp::safeFindNamespace\fP (void *data)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Rcpp from the source code.
