.TH "src/Evaluator.cpp" 3 "2 Jan 2010" "Rcpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Evaluator.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Rcpp/Evaluator.h>\fP
.br
\fC#include <Rcpp/Environment.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBRcpp\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Rcpp from the source code.
