.TH "src/exceptions.cpp" 3 "2 Jan 2010" "Rcpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/exceptions.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Rcpp.h>\fP
.br
\fC#include <typeinfo>\fP
.br
\fC#include <exception>\fP
.br
\fC#include <exception_defines.h>\fP
.br
\fC#include <cxxabi.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBforward_uncaught_exceptions_to_r\fP ()"
.br
.ti -1c
.RI "SEXP \fBinitUncaughtExceptionHandler\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void forward_uncaught_exceptions_to_r ()"
.PP
Definition at line 29 of file exceptions.cpp.
.PP
Referenced by initUncaughtExceptionHandler().
.SS "SEXP initUncaughtExceptionHandler ()"
.PP
Definition at line 77 of file exceptions.cpp.
.PP
References forward_uncaught_exceptions_to_r().
.SH "Author"
.PP 
Generated automatically by Doxygen for Rcpp from the source code.
