.TH "RcppDateVector" 3 "19 Dec 2009" "Rcpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RcppDateVector \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RcppDateVector.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRcppDateVector\fP (SEXP vec)"
.br
.ti -1c
.RI "\fB~RcppDateVector\fP ()"
.br
.ti -1c
.RI "\fBRcppDate\fP & \fBoperator()\fP (int i)"
.br
.ti -1c
.RI "int \fBsize\fP () const "
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBRcppDate\fP * \fBv\fP"
.br
.ti -1c
.RI "int \fBlength\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 29 of file RcppDateVector.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RcppDateVector::RcppDateVector (SEXP vec)"
.PP
Definition at line 25 of file RcppDateVector.cpp.
.PP
References length, and v.
.SS "RcppDateVector::~RcppDateVector ()"
.PP
Definition at line 38 of file RcppDateVector.cpp.
.PP
References v.
.SH "Member Function Documentation"
.PP 
.SS "\fBRcppDate\fP & RcppDateVector::operator() (int i)"
.PP
Definition at line 42 of file RcppDateVector.cpp.
.PP
References length, and v.
.SS "int RcppDateVector::size () const"
.PP
Definition at line 51 of file RcppDateVector.cpp.
.PP
References length.
.PP
Referenced by RcppResultSet::add(), and RcppDateExample().
.SH "Member Data Documentation"
.PP 
.SS "int \fBRcppDateVector::length\fP\fC [private]\fP"
.PP
Definition at line 37 of file RcppDateVector.h.
.PP
Referenced by operator()(), RcppDateVector(), and size().
.SS "\fBRcppDate\fP* \fBRcppDateVector::v\fP\fC [private]\fP"
.PP
Definition at line 36 of file RcppDateVector.h.
.PP
Referenced by operator()(), RcppDateVector(), and ~RcppDateVector().

.SH "Author"
.PP 
Generated automatically by Doxygen for Rcpp from the source code.
