.TH "RcppVectorView" 3 "6 Nov 2009" "Rcpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RcppVectorView \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Rcpp.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRcppVectorView\fP (SEXP vec)"
.br
.ti -1c
.RI "int \fBsize\fP () const "
.br
.ti -1c
.RI "T \fBoperator()\fP (int i) const "
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fBlen\fP"
.br
.ti -1c
.RI "T * \fBv\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T> class RcppVectorView< T >"

.PP
Definition at line 474 of file Rcpp.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > \fBRcppVectorView\fP< T >::\fBRcppVectorView\fP (SEXP vec)\fC [inline]\fP"
.PP
Definition at line 424 of file Rcpp.cpp.
.PP
References RcppVectorView< T >::len, and RcppVectorView< T >::v.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > T \fBRcppVectorView\fP< T >::operator() (int i) const\fC [inline]\fP"
.PP
Definition at line 478 of file Rcpp.h.
.PP
References RcppVectorView< T >::len, and RcppVectorView< T >::v.
.SS "template<typename T > int \fBRcppVectorView\fP< T >::size () const\fC [inline]\fP"
.PP
Definition at line 477 of file Rcpp.h.
.PP
References RcppVectorView< T >::len.
.SH "Member Data Documentation"
.PP 
.SS "template<typename T > int \fBRcppVectorView\fP< T >::\fBlen\fP\fC [private]\fP"
.PP
Definition at line 487 of file Rcpp.h.
.PP
Referenced by RcppVectorView< T >::operator()(), RcppVectorView< T >::RcppVectorView(), and RcppVectorView< T >::size().
.SS "template<typename T > T* \fBRcppVectorView\fP< T >::\fBv\fP\fC [private]\fP"
.PP
Definition at line 488 of file Rcpp.h.
.PP
Referenced by RcppVectorView< T >::operator()(), and RcppVectorView< T >::RcppVectorView().

.SH "Author"
.PP 
Generated automatically by Doxygen for Rcpp from the source code.
