.TH "RcppVector" 3 "6 Nov 2009" "Rcpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RcppVector \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Rcpp.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRcppVector\fP (SEXP vec)"
.br
.ti -1c
.RI "\fBRcppVector\fP (int \fBlen\fP)"
.br
.ti -1c
.RI "int \fBsize\fP ()"
.br
.ti -1c
.RI "T & \fBoperator()\fP (int i)"
.br
.ti -1c
.RI "T * \fBcVector\fP ()"
.br
.ti -1c
.RI "std::vector< T > \fBstlVector\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fBlen\fP"
.br
.ti -1c
.RI "T * \fBv\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T> class RcppVector< T >"

.PP
Definition at line 360 of file Rcpp.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > \fBRcppVector\fP< T >::\fBRcppVector\fP (SEXP vec)\fC [inline]\fP"
.PP
Definition at line 299 of file Rcpp.cpp.
.PP
References RcppVector< T >::len, and RcppVector< T >::v.
.SS "template<typename T > \fBRcppVector\fP< T >::\fBRcppVector\fP (int len)\fC [inline]\fP"
.PP
Definition at line 323 of file Rcpp.cpp.
.PP
References RcppVector< T >::len, and RcppVector< T >::v.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > T * \fBRcppVector\fP< T >::cVector ()\fC [inline]\fP"
.PP
Definition at line 331 of file Rcpp.cpp.
.PP
References RcppVector< T >::len, and RcppVector< T >::v.
.PP
Referenced by RcppResultSet::add(), and Rcpp_Example().
.SS "template<typename T> T& \fBRcppVector\fP< T >::operator() (int i)\fC [inline]\fP"
.PP
Definition at line 365 of file Rcpp.h.
.PP
References RcppVector< T >::v.
.SS "template<typename T> int \fBRcppVector\fP< T >::size ()\fC [inline]\fP"
.PP
Definition at line 364 of file Rcpp.h.
.PP
Referenced by RcppResultSet::add(), Rcpp_Example(), and RcppVectorExample().
.SS "template<typename T > std::vector< T > \fBRcppVector\fP< T >::stlVector ()\fC [inline]\fP"
.PP
Definition at line 339 of file Rcpp.cpp.
.PP
References RcppVector< T >::len, and RcppVector< T >::v.
.PP
Referenced by Rcpp_Example().
.SH "Member Data Documentation"
.PP 
.SS "template<typename T> int \fBRcppVector\fP< T >::\fBlen\fP\fC [private]\fP"
.PP
Definition at line 376 of file Rcpp.h.
.PP
Referenced by RcppVector< T >::cVector(), RcppVector< T >::RcppVector(), and RcppVector< T >::stlVector().
.SS "template<typename T> T* \fBRcppVector\fP< T >::\fBv\fP\fC [private]\fP"
.PP
Definition at line 377 of file Rcpp.h.
.PP
Referenced by RcppVector< T >::cVector(), RcppVector< T >::operator()(), RcppVector< T >::RcppVector(), and RcppVector< T >::stlVector().

.SH "Author"
.PP 
Generated automatically by Doxygen for Rcpp from the source code.
