.TH "RcppFrame" 3 "19 Dec 2009" "Rcpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RcppFrame \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RcppFrame.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRcppFrame\fP (SEXP df)"
.br
.ti -1c
.RI "\fBRcppFrame\fP (std::vector< std::string > \fBcolNames\fP)"
.br
.ti -1c
.RI "std::vector< std::string > & \fBgetColNames\fP ()"
.br
.ti -1c
.RI "std::vector< std::vector< \fBColDatum\fP > > & \fBgetTableData\fP ()"
.br
.ti -1c
.RI "void \fBaddRow\fP (std::vector< \fBColDatum\fP > rowData)"
.br
.ti -1c
.RI "int \fBrows\fP ()"
.br
.ti -1c
.RI "int \fBcols\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::vector< std::string > \fBcolNames\fP"
.br
.ti -1c
.RI "std::vector< std::vector< \fBColDatum\fP > > \fBtable\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 37 of file RcppFrame.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RcppFrame::RcppFrame (SEXP df)"
.PP
Definition at line 167 of file RcppFrame.cpp.
.PP
References colNames, and table.
.SS "RcppFrame::RcppFrame (std::vector< std::string > colNames)"
.PP
Definition at line 162 of file RcppFrame.cpp.
.SH "Member Function Documentation"
.PP 
.SS "void RcppFrame::addRow (std::vector< \fBColDatum\fP > rowData)"
.PP
Definition at line 248 of file RcppFrame.cpp.
.PP
References colNames, and table.
.PP
Referenced by Rcpp_Example().
.SS "int RcppFrame::cols ()"
.PP
Definition at line 271 of file RcppFrame.cpp.
.PP
References table.
.SS "std::vector< std::string > & RcppFrame::getColNames ()"
.PP
Definition at line 240 of file RcppFrame.cpp.
.PP
References colNames.
.PP
Referenced by RcppResultSet::add().
.SS "std::vector< std::vector< \fBColDatum\fP > > & RcppFrame::getTableData ()"
.PP
Definition at line 244 of file RcppFrame.cpp.
.PP
References table.
.PP
Referenced by RcppResultSet::add().
.SS "int RcppFrame::rows ()"
.PP
Definition at line 267 of file RcppFrame.cpp.
.PP
References table.
.SH "Member Data Documentation"
.PP 
.SS "std::vector<std::string> \fBRcppFrame::colNames\fP\fC [private]\fP"
.PP
Definition at line 38 of file RcppFrame.h.
.PP
Referenced by addRow(), getColNames(), and RcppFrame().
.SS "std::vector<std::vector<\fBColDatum\fP> > \fBRcppFrame::table\fP\fC [private]\fP"
.PP
Definition at line 39 of file RcppFrame.h.
.PP
Referenced by addRow(), cols(), getTableData(), RcppFrame(), and rows().

.SH "Author"
.PP 
Generated automatically by Doxygen for Rcpp from the source code.
