.TH "src/RcppDatetime.h" 3 "19 Dec 2009" "Rcpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/RcppDatetime.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <RcppCommon.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRcppDatetime\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Rcpp from the source code.
