.TH "src/RcppFrame.h" 3 "19 Dec 2009" "Rcpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/RcppFrame.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <RcppCommon.h>\fP
.br
\fC#include <RcppDate.h>\fP
.br
\fC#include <RcppDatetime.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRcppFrame\fP"
.br
.ti -1c
.RI "class \fBColDatum\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBColType\fP { \fBCOLTYPE_DOUBLE\fP, \fBCOLTYPE_INT\fP, \fBCOLTYPE_STRING\fP, \fBCOLTYPE_FACTOR\fP, \fBCOLTYPE_LOGICAL\fP, \fBCOLTYPE_DATE\fP, \fBCOLTYPE_DATETIME\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBColType\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fICOLTYPE_DOUBLE \fP\fP
.TP
\fB\fICOLTYPE_INT \fP\fP
.TP
\fB\fICOLTYPE_STRING \fP\fP
.TP
\fB\fICOLTYPE_FACTOR \fP\fP
.TP
\fB\fICOLTYPE_LOGICAL \fP\fP
.TP
\fB\fICOLTYPE_DATE \fP\fP
.TP
\fB\fICOLTYPE_DATETIME \fP\fP

.PP
Definition at line 30 of file RcppFrame.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for Rcpp from the source code.
