.TH "src/RcppCommon.cpp" 3 "2 Jan 2010" "Rcpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/RcppCommon.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Rcpp.h>\fP
.br
\fC#include <cstring>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBcopyMessageToR\fP (const char *const mesg)"
.br
.ti -1c
.RI "void \fBlogTxtFunction\fP (const char *file, const int line, const char *expression)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* copyMessageToR (const char *const  mesg)"
.PP
Definition at line 29 of file RcppCommon.cpp.
.PP
Referenced by Rcpp_Example(), RcppDateExample(), RcppParamsExample(), and RcppVectorExample().
.SS "void logTxtFunction (const char * file, const int line, const char * expression)\fC [inline]\fP"
.PP
Definition at line 39 of file RcppCommon.cpp.
.SH "Author"
.PP 
Generated automatically by Doxygen for Rcpp from the source code.
