.TH "src/RcppFunction.h" 3 "19 Dec 2009" "Rcpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/RcppFunction.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <RcppCommon.h>\fP
.br
\fC#include <RcppDate.h>\fP
.br
\fC#include <RcppDatetime.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRcppFunction\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Rcpp from the source code.
