.TH "src/Rcpp.h" 3 "2 Jan 2010" "Rcpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Rcpp.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <RcppCommon.h>\fP
.br
\fC#include <RcppDate.h>\fP
.br
\fC#include <RcppDateVector.h>\fP
.br
\fC#include <RcppDatetime.h>\fP
.br
\fC#include <RcppDatetimeVector.h>\fP
.br
\fC#include <RcppFrame.h>\fP
.br
\fC#include <RcppFunction.h>\fP
.br
\fC#include <RcppList.h>\fP
.br
\fC#include <RcppMatrix.h>\fP
.br
\fC#include <RcppMatrixView.h>\fP
.br
\fC#include <RcppNumList.h>\fP
.br
\fC#include <RcppParams.h>\fP
.br
\fC#include <RcppResultSet.h>\fP
.br
\fC#include <RcppStringVector.h>\fP
.br
\fC#include <RcppStringVectorView.h>\fP
.br
\fC#include <RcppVector.h>\fP
.br
\fC#include <RcppVectorView.h>\fP
.br
\fC#include <Rcpp/RObject.h>\fP
.br
\fC#include <Rcpp/XPtr.h>\fP
.br
\fC#include <Rcpp/Environment.h>\fP
.br
\fC#include <Rcpp/Evaluator.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Rcpp from the source code.
