.TH "Rcpp::safeAssign_s" 3 "2 Jan 2010" "Rcpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Rcpp::safeAssign_s \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "SEXP \fBsym\fP"
.br
.ti -1c
.RI "SEXP \fBval\fP"
.br
.ti -1c
.RI "SEXP \fBrho\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file Environment.cpp.
.SH "Member Data Documentation"
.PP 
.SS "SEXP \fBRcpp::safeAssign_s::rho\fP"
.PP
Definition at line 29 of file Environment.cpp.
.PP
Referenced by Rcpp::safeAssign().
.SS "SEXP \fBRcpp::safeAssign_s::sym\fP"
.PP
Definition at line 29 of file Environment.cpp.
.PP
Referenced by Rcpp::safeAssign().
.SS "SEXP \fBRcpp::safeAssign_s::val\fP"
.PP
Definition at line 29 of file Environment.cpp.
.PP
Referenced by Rcpp::safeAssign().

.SH "Author"
.PP 
Generated automatically by Doxygen for Rcpp from the source code.
