.TH "src/RcppResultSet.h" 3 "19 Dec 2009" "Rcpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/RcppResultSet.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <RcppCommon.h>\fP
.br
\fC#include <RcppDate.h>\fP
.br
\fC#include <RcppDateVector.h>\fP
.br
\fC#include <RcppDatetime.h>\fP
.br
\fC#include <RcppDatetimeVector.h>\fP
.br
\fC#include <RcppStringVector.h>\fP
.br
\fC#include <RcppFrame.h>\fP
.br
\fC#include <RcppList.h>\fP
.br
\fC#include <RcppMatrix.h>\fP
.br
\fC#include <RcppNumList.h>\fP
.br
\fC#include <RcppVector.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRcppResultSet\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Rcpp from the source code.
