.TH "RcppNumList" 3 "3 Aug 2009" "Rcpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RcppNumList \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Rcpp.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRcppNumList\fP (SEXP theList)"
.br
.ti -1c
.RI "std::string \fBgetName\fP (int i)"
.br
.ti -1c
.RI "double \fBgetValue\fP (int i)"
.br
.ti -1c
.RI "int \fBsize\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fBlen\fP"
.br
.ti -1c
.RI "SEXP \fBnamedList\fP"
.br
.ti -1c
.RI "SEXP \fBnames\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 319 of file Rcpp.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RcppNumList::RcppNumList (SEXP theList)\fC [inline]\fP"
.PP
Definition at line 321 of file Rcpp.h.
.PP
References len, namedList, and names.
.SH "Member Function Documentation"
.PP 
.SS "std::string RcppNumList::getName (int i)\fC [inline]\fP"
.PP
Definition at line 328 of file Rcpp.h.
.PP
References len, and names.
.PP
Referenced by Rcpp_Example().
.SS "double RcppNumList::getValue (int i)\fC [inline]\fP"
.PP
Definition at line 336 of file Rcpp.h.
.PP
References len, and namedList.
.PP
Referenced by Rcpp_Example().
.SS "int RcppNumList::size ()\fC [inline]\fP"
.PP
Definition at line 351 of file Rcpp.h.
.PP
References len.
.SH "Member Data Documentation"
.PP 
.SS "int \fBRcppNumList::len\fP\fC [private]\fP"
.PP
Definition at line 353 of file Rcpp.h.
.PP
Referenced by getName(), getValue(), RcppNumList(), and size().
.SS "SEXP \fBRcppNumList::namedList\fP\fC [private]\fP"
.PP
Definition at line 354 of file Rcpp.h.
.PP
Referenced by getValue(), and RcppNumList().
.SS "SEXP \fBRcppNumList::names\fP\fC [private]\fP"
.PP
Definition at line 355 of file Rcpp.h.
.PP
Referenced by getName(), and RcppNumList().

.SH "Author"
.PP 
Generated automatically by Doxygen for Rcpp from the source code.
