.TH "RcppMatrix" 3 "6 Nov 2009" "Rcpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RcppMatrix \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Rcpp.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRcppMatrix\fP (SEXP mat)"
.br
.ti -1c
.RI "\fBRcppMatrix\fP (int nx, int ny)"
.br
.ti -1c
.RI "int \fBgetDim1\fP ()"
.br
.ti -1c
.RI "int \fBgetDim2\fP ()"
.br
.ti -1c
.RI "int \fBrows\fP ()"
.br
.ti -1c
.RI "int \fBcols\fP ()"
.br
.ti -1c
.RI "T & \fBoperator()\fP (int i, int j)"
.br
.ti -1c
.RI "T ** \fBcMatrix\fP ()"
.br
.ti -1c
.RI "std::vector< std::vector< T > > \fBstlMatrix\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fBdim1\fP"
.br
.ti -1c
.RI "int \fBdim2\fP"
.br
.ti -1c
.RI "T ** \fBa\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T> class RcppMatrix< T >"

.PP
Definition at line 447 of file Rcpp.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > \fBRcppMatrix\fP< T >::\fBRcppMatrix\fP (SEXP mat)\fC [inline]\fP"
.PP
Definition at line 347 of file Rcpp.cpp.
.PP
References RcppMatrix< T >::a, RcppMatrix< T >::dim1, and RcppMatrix< T >::dim2.
.SS "template<typename T > \fBRcppMatrix\fP< T >::\fBRcppMatrix\fP (int nx, int ny)\fC [inline]\fP"
.PP
Definition at line 378 of file Rcpp.cpp.
.PP
References RcppMatrix< T >::a, RcppMatrix< T >::dim1, and RcppMatrix< T >::dim2.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > T ** \fBRcppMatrix\fP< T >::cMatrix ()\fC [inline]\fP"
.PP
Definition at line 405 of file Rcpp.cpp.
.PP
References RcppMatrix< T >::a, RcppMatrix< T >::dim1, and RcppMatrix< T >::dim2.
.PP
Referenced by RcppResultSet::add(), and Rcpp_Example().
.SS "template<typename T> int \fBRcppMatrix\fP< T >::cols ()\fC [inline]\fP"
.PP
Definition at line 454 of file Rcpp.h.
.PP
References RcppMatrix< T >::dim2.
.SS "template<typename T> int \fBRcppMatrix\fP< T >::getDim1 ()\fC [inline]\fP"
.PP
Definition at line 451 of file Rcpp.h.
.PP
References RcppMatrix< T >::dim1.
.PP
Referenced by RcppResultSet::add(), and Rcpp_Example().
.SS "template<typename T> int \fBRcppMatrix\fP< T >::getDim2 ()\fC [inline]\fP"
.PP
Definition at line 452 of file Rcpp.h.
.PP
References RcppMatrix< T >::dim2.
.PP
Referenced by RcppResultSet::add(), and Rcpp_Example().
.SS "template<typename T> T& \fBRcppMatrix\fP< T >::operator() (int i, int j)\fC [inline]\fP"
.PP
Definition at line 455 of file Rcpp.h.
.PP
References RcppMatrix< T >::a, RcppMatrix< T >::dim1, and RcppMatrix< T >::dim2.
.SS "template<typename T> int \fBRcppMatrix\fP< T >::rows ()\fC [inline]\fP"
.PP
Definition at line 453 of file Rcpp.h.
.PP
References RcppMatrix< T >::dim1.
.SS "template<typename T > std::vector< std::vector< T > > \fBRcppMatrix\fP< T >::stlMatrix ()\fC [inline]\fP"
.PP
Definition at line 392 of file Rcpp.cpp.
.PP
References RcppMatrix< T >::a, RcppMatrix< T >::dim1, and RcppMatrix< T >::dim2.
.PP
Referenced by Rcpp_Example().
.SH "Member Data Documentation"
.PP 
.SS "template<typename T> T** \fBRcppMatrix\fP< T >::\fBa\fP\fC [private]\fP"
.PP
Definition at line 467 of file Rcpp.h.
.PP
Referenced by RcppMatrix< T >::cMatrix(), RcppMatrix< T >::operator()(), RcppMatrix< T >::RcppMatrix(), and RcppMatrix< T >::stlMatrix().
.SS "template<typename T> int \fBRcppMatrix\fP< T >::\fBdim1\fP\fC [private]\fP"
.PP
Definition at line 466 of file Rcpp.h.
.PP
Referenced by RcppMatrix< T >::cMatrix(), RcppMatrix< T >::getDim1(), RcppMatrix< T >::operator()(), RcppMatrix< T >::RcppMatrix(), RcppMatrix< T >::rows(), and RcppMatrix< T >::stlMatrix().
.SS "template<typename T> int \fBRcppMatrix\fP< T >::\fBdim2\fP\fC [private]\fP"
.PP
Definition at line 466 of file Rcpp.h.
.PP
Referenced by RcppMatrix< T >::cMatrix(), RcppMatrix< T >::cols(), RcppMatrix< T >::getDim2(), RcppMatrix< T >::operator()(), RcppMatrix< T >::RcppMatrix(), and RcppMatrix< T >::stlMatrix().

.SH "Author"
.PP 
Generated automatically by Doxygen for Rcpp from the source code.
