.TH "RcppStringVector" 3 "2 Jan 2010" "Rcpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RcppStringVector \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RcppStringVector.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRcppStringVector\fP (SEXP vec)"
.br
.ti -1c
.RI "\fB~RcppStringVector\fP ()"
.br
.ti -1c
.RI "std::string & \fBoperator()\fP (int i) const "
.br
.ti -1c
.RI "int \fBsize\fP () const "
.br
.ti -1c
.RI "std::vector< std::string > \fBstlVector\fP () const "
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::string * \fBv\fP"
.br
.ti -1c
.RI "int \fBlength\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file RcppStringVector.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RcppStringVector::RcppStringVector (SEXP vec)"
.PP
Definition at line 25 of file RcppStringVector.cpp.
.PP
References length, and v.
.SS "RcppStringVector::~RcppStringVector ()"
.PP
Definition at line 40 of file RcppStringVector.cpp.
.PP
References v.
.SH "Member Function Documentation"
.PP 
.SS "std::string & RcppStringVector::operator() (int i) const"
.PP
Definition at line 44 of file RcppStringVector.cpp.
.PP
References length, and v.
.SS "int RcppStringVector::size () const"
.PP
Definition at line 53 of file RcppStringVector.cpp.
.PP
References length.
.PP
Referenced by RcppResultSet::add().
.SS "std::vector< std::string > RcppStringVector::stlVector () const"
.PP
Definition at line 57 of file RcppStringVector.cpp.
.PP
References length, and v.
.SH "Member Data Documentation"
.PP 
.SS "int \fBRcppStringVector::length\fP\fC [private]\fP"
.PP
Definition at line 37 of file RcppStringVector.h.
.PP
Referenced by operator()(), RcppStringVector(), size(), and stlVector().
.SS "std::string* \fBRcppStringVector::v\fP\fC [private]\fP"
.PP
Definition at line 36 of file RcppStringVector.h.
.PP
Referenced by operator()(), RcppStringVector(), stlVector(), and ~RcppStringVector().

.SH "Author"
.PP 
Generated automatically by Doxygen for Rcpp from the source code.
