.TH "RcppDatetime" 3 "2 Jan 2010" "Rcpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RcppDatetime \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RcppDatetime.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRcppDatetime\fP (void)"
.br
.ti -1c
.RI "\fBRcppDatetime\fP (const double d)"
.br
.ti -1c
.RI "double \fBgetFractionalTimestamp\fP (void) const "
.br
.ti -1c
.RI "int \fBgetYear\fP (void)"
.br
.ti -1c
.RI "int \fBgetMonth\fP (void)"
.br
.ti -1c
.RI "int \fBgetDay\fP (void)"
.br
.ti -1c
.RI "int \fBgetWeekday\fP (void)"
.br
.ti -1c
.RI "int \fBgetHour\fP (void)"
.br
.ti -1c
.RI "int \fBgetMinute\fP (void)"
.br
.ti -1c
.RI "int \fBgetSecond\fP (void)"
.br
.ti -1c
.RI "int \fBgetMicroSec\fP (void)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBparseTime\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "double \fBm_d\fP"
.br
.ti -1c
.RI "bool \fBm_parsed\fP"
.br
.ti -1c
.RI "int \fBm_us\fP"
.br
.ti -1c
.RI "struct tm \fBm_tm\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBColDatum\fP"
.br
.ti -1c
.RI "double \fBoperator-\fP (const \fBRcppDatetime\fP &dt1, const \fBRcppDatetime\fP &dt2)"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBRcppDatetime\fP &dt1, const \fBRcppDatetime\fP &dt2)"
.br
.ti -1c
.RI "bool \fBoperator<=\fP (const \fBRcppDatetime\fP &dt1, const \fBRcppDatetime\fP &dt2)"
.br
.ti -1c
.RI "bool \fBoperator>\fP (const \fBRcppDatetime\fP &dt1, const \fBRcppDatetime\fP &dt2)"
.br
.ti -1c
.RI "bool \fBoperator>=\fP (const \fBRcppDatetime\fP &dt1, const \fBRcppDatetime\fP &dt2)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBRcppDatetime\fP &dt1, const \fBRcppDatetime\fP &dt2)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBRcppDatetime\fP &datetime)"
.br
.ti -1c
.RI "\fBRcppDatetime\fP \fBoperator+\fP (const \fBRcppDatetime\fP &date, double offset)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 27 of file RcppDatetime.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RcppDatetime::RcppDatetime (void)"
.PP
Definition at line 24 of file RcppDatetime.cpp.
.SS "RcppDatetime::RcppDatetime (const double d)"
.PP
Definition at line 29 of file RcppDatetime.cpp.
.SH "Member Function Documentation"
.PP 
.SS "int RcppDatetime::getDay (void)\fC [inline]\fP"
.PP
Definition at line 45 of file RcppDatetime.h.
.PP
References m_parsed, m_tm, and parseTime().
.SS "double RcppDatetime::getFractionalTimestamp (void) const\fC [inline]\fP"
.PP
Definition at line 42 of file RcppDatetime.h.
.PP
References m_d.
.PP
Referenced by RcppResultSet::add(), and RcppFunction::appendToRList().
.SS "int RcppDatetime::getHour (void)\fC [inline]\fP"
.PP
Definition at line 47 of file RcppDatetime.h.
.PP
References m_parsed, m_tm, and parseTime().
.SS "int RcppDatetime::getMicroSec (void)\fC [inline]\fP"
.PP
Definition at line 50 of file RcppDatetime.h.
.PP
References m_parsed, m_us, and parseTime().
.SS "int RcppDatetime::getMinute (void)\fC [inline]\fP"
.PP
Definition at line 48 of file RcppDatetime.h.
.PP
References m_parsed, m_tm, and parseTime().
.SS "int RcppDatetime::getMonth (void)\fC [inline]\fP"
.PP
Definition at line 44 of file RcppDatetime.h.
.PP
References m_parsed, m_tm, and parseTime().
.SS "int RcppDatetime::getSecond (void)\fC [inline]\fP"
.PP
Definition at line 49 of file RcppDatetime.h.
.PP
References m_parsed, m_tm, and parseTime().
.SS "int RcppDatetime::getWeekday (void)\fC [inline]\fP"
.PP
Definition at line 46 of file RcppDatetime.h.
.PP
References m_parsed, m_tm, and parseTime().
.SS "int RcppDatetime::getYear (void)\fC [inline]\fP"
.PP
Definition at line 43 of file RcppDatetime.h.
.PP
References m_parsed, m_tm, and parseTime().
.SS "void RcppDatetime::parseTime ()\fC [private]\fP"
.PP
Definition at line 34 of file RcppDatetime.cpp.
.PP
References m_d, m_parsed, m_tm, and m_us.
.PP
Referenced by getDay(), getHour(), getMicroSec(), getMinute(), getMonth(), getSecond(), getWeekday(), getYear(), and operator<<().
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBColDatum\fP\fC [friend]\fP"
.PP
Definition at line 36 of file RcppDatetime.h.
.SS "\fBRcppDatetime\fP operator+ (const \fBRcppDatetime\fP & date, double offset)\fC [friend]\fP"
.SS "double operator- (const \fBRcppDatetime\fP & dt1, const \fBRcppDatetime\fP & dt2)\fC [friend]\fP"
.PP
Definition at line 52 of file RcppDatetime.h.
.SS "bool operator< (const \fBRcppDatetime\fP & dt1, const \fBRcppDatetime\fP & dt2)\fC [friend]\fP"
.PP
Definition at line 53 of file RcppDatetime.h.
.SS "std::ostream& operator<< (std::ostream & os, const \fBRcppDatetime\fP & datetime)\fC [friend]\fP"
.SS "bool operator<= (const \fBRcppDatetime\fP & dt1, const \fBRcppDatetime\fP & dt2)\fC [friend]\fP"
.PP
Definition at line 54 of file RcppDatetime.h.
.SS "bool operator== (const \fBRcppDatetime\fP & dt1, const \fBRcppDatetime\fP & dt2)\fC [friend]\fP"
.PP
Definition at line 57 of file RcppDatetime.h.
.SS "bool operator> (const \fBRcppDatetime\fP & dt1, const \fBRcppDatetime\fP & dt2)\fC [friend]\fP"
.PP
Definition at line 55 of file RcppDatetime.h.
.SS "bool operator>= (const \fBRcppDatetime\fP & dt1, const \fBRcppDatetime\fP & dt2)\fC [friend]\fP"
.PP
Definition at line 56 of file RcppDatetime.h.
.SH "Member Data Documentation"
.PP 
.SS "double \fBRcppDatetime::m_d\fP\fC [private]\fP"
.PP
Definition at line 29 of file RcppDatetime.h.
.PP
Referenced by getFractionalTimestamp(), operator+(), parseTime(), and ColDatum::setDatetimeValue().
.SS "bool \fBRcppDatetime::m_parsed\fP\fC [private]\fP"
.PP
Definition at line 30 of file RcppDatetime.h.
.PP
Referenced by getDay(), getHour(), getMicroSec(), getMinute(), getMonth(), getSecond(), getWeekday(), getYear(), operator+(), and parseTime().
.SS "struct tm \fBRcppDatetime::m_tm\fP\fC [read, private]\fP"
.PP
Definition at line 32 of file RcppDatetime.h.
.PP
Referenced by getDay(), getHour(), getMinute(), getMonth(), getSecond(), getWeekday(), getYear(), operator<<(), and parseTime().
.SS "int \fBRcppDatetime::m_us\fP\fC [private]\fP"
.PP
Definition at line 31 of file RcppDatetime.h.
.PP
Referenced by getMicroSec(), operator<<(), and parseTime().

.SH "Author"
.PP 
Generated automatically by Doxygen for Rcpp from the source code.
