.TH "Rcpp::safeFindNamespace_s" 3 "2 Jan 2010" "Rcpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Rcpp::safeFindNamespace_s \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "SEXP \fBsym\fP"
.br
.ti -1c
.RI "SEXP \fBval\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 36 of file Environment.cpp.
.SH "Member Data Documentation"
.PP 
.SS "SEXP \fBRcpp::safeFindNamespace_s::sym\fP"
.PP
Definition at line 37 of file Environment.cpp.
.PP
Referenced by Rcpp::safeFindNamespace().
.SS "SEXP \fBRcpp::safeFindNamespace_s::val\fP"
.PP
Definition at line 37 of file Environment.cpp.
.PP
Referenced by Rcpp::safeFindNamespace().

.SH "Author"
.PP 
Generated automatically by Doxygen for Rcpp from the source code.
