.TH "src/RcppSexp.h" 3 "2 Jan 2010" "Rcpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/RcppSexp.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <RcppCommon.h>\fP
.br
\fC#include <set>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRcppSexp\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Rcpp from the source code.
