.TH "RcppSexp" 3 "2 Jan 2010" "Rcpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RcppSexp \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RcppSexp.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRcppSexp\fP (SEXP m_sexp=R_NilValue)"
.br
.ti -1c
.RI "\fB~RcppSexp\fP ()"
.br
.ti -1c
.RI "\fBRcppSexp\fP (const double &v)"
.br
.ti -1c
.RI "\fBRcppSexp\fP (const int &v)"
.br
.ti -1c
.RI "\fBRcppSexp\fP (const Rbyte &v)"
.br
.ti -1c
.RI "\fBRcppSexp\fP (const std::string &v)"
.br
.ti -1c
.RI "\fBRcppSexp\fP (const bool &v)"
.br
.ti -1c
.RI "\fBRcppSexp\fP (const std::vector< int > &v)"
.br
.ti -1c
.RI "\fBRcppSexp\fP (const std::vector< double > &v)"
.br
.ti -1c
.RI "\fBRcppSexp\fP (const std::vector< std::string > &v)"
.br
.ti -1c
.RI "\fBRcppSexp\fP (const std::vector< Rbyte > &v)"
.br
.ti -1c
.RI "\fBRcppSexp\fP (const std::vector< bool > &v)"
.br
.ti -1c
.RI "\fBRcppSexp\fP (const std::set< int > &v)"
.br
.ti -1c
.RI "\fBRcppSexp\fP (const std::set< double > &v)"
.br
.ti -1c
.RI "\fBRcppSexp\fP (const std::set< std::string > &v)"
.br
.ti -1c
.RI "\fBRcppSexp\fP (const std::set< Rbyte > &v)"
.br
.ti -1c
.RI "bool \fBasBool\fP () const "
.br
.ti -1c
.RI "double \fBasDouble\fP () const "
.br
.ti -1c
.RI "int \fBasInt\fP () const "
.br
.ti -1c
.RI "Rbyte \fBasRaw\fP () const "
.br
.ti -1c
.RI "std::string \fBasStdString\fP () const "
.br
.ti -1c
.RI "std::vector< int > \fBasStdVectorInt\fP () const "
.br
.ti -1c
.RI "std::vector< double > \fBasStdVectorDouble\fP () const "
.br
.ti -1c
.RI "std::vector< std::string > \fBasStdVectorString\fP () const "
.br
.ti -1c
.RI "std::vector< Rbyte > \fBasStdVectorRaw\fP () const "
.br
.ti -1c
.RI "std::vector< bool > \fBasStdVectorBool\fP () const "
.br
.ti -1c
.RI "void \fBprotect\fP ()"
.br
.ti -1c
.RI "void \fBrelease\fP ()"
.br
.ti -1c
.RI "\fBoperator SEXP\fP () const "
.br
.ti -1c
.RI "std::vector< std::string > \fBattributeNames\fP () const "
.br
.ti -1c
.RI "bool \fBhasAttribute\fP (const std::string &attr) const "
.br
.ti -1c
.RI "SEXP \fBattr\fP (const std::string &name) const "
.br
.ti -1c
.RI "bool \fBisNULL\fP () const "
.br
.ti -1c
.RI "int \fBsexp_type\fP () const "
.br
.ti -1c
.RI "SEXP \fBasSexp\fP () const "
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBDEPRECATED\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "Rcpp::RObject \fBobject\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class is DEPRECATED, will be DEFUNCT in a next version and eventually removed from \fBRcpp\fP.
.PP
The alternative is to use the Rcpp::RObject class and the set of functions \fBRcpp::wrap\fP. 
.PP
Definition at line 35 of file RcppSexp.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RcppSexp::RcppSexp (SEXP m_sexp = \fCR_NilValue\fP)\fC [inline]\fP"wraps the SEXP into an Rcpp::RObject. The RObject does not automatically enforce protection of the SEXP, so if you want to preserve the SEXP from R garbage collection, you must call the protect member function 
.PP
Definition at line 44 of file RcppSexp.h.
.PP
References DEPRECATED().
.SS "RcppSexp::~RcppSexp ()"
.SS "RcppSexp::RcppSexp (const double & v)\fC [inline]\fP"
.PP
Definition at line 50 of file RcppSexp.h.
.PP
References DEPRECATED().
.SS "RcppSexp::RcppSexp (const int & v)\fC [inline]\fP"
.PP
Definition at line 51 of file RcppSexp.h.
.PP
References DEPRECATED().
.SS "RcppSexp::RcppSexp (const Rbyte & v)\fC [inline]\fP"
.PP
Definition at line 52 of file RcppSexp.h.
.PP
References DEPRECATED().
.SS "RcppSexp::RcppSexp (const std::string & v)\fC [inline]\fP"
.PP
Definition at line 53 of file RcppSexp.h.
.PP
References DEPRECATED().
.SS "RcppSexp::RcppSexp (const bool & v)\fC [inline]\fP"
.PP
Definition at line 54 of file RcppSexp.h.
.PP
References DEPRECATED().
.SS "RcppSexp::RcppSexp (const std::vector< int > & v)\fC [inline]\fP"
.PP
Definition at line 56 of file RcppSexp.h.
.PP
References DEPRECATED().
.SS "RcppSexp::RcppSexp (const std::vector< double > & v)\fC [inline]\fP"
.PP
Definition at line 57 of file RcppSexp.h.
.PP
References DEPRECATED().
.SS "RcppSexp::RcppSexp (const std::vector< std::string > & v)\fC [inline]\fP"
.PP
Definition at line 58 of file RcppSexp.h.
.PP
References DEPRECATED().
.SS "RcppSexp::RcppSexp (const std::vector< Rbyte > & v)\fC [inline]\fP"
.PP
Definition at line 59 of file RcppSexp.h.
.PP
References DEPRECATED().
.SS "RcppSexp::RcppSexp (const std::vector< bool > & v)\fC [inline]\fP"
.PP
Definition at line 60 of file RcppSexp.h.
.PP
References DEPRECATED().
.SS "RcppSexp::RcppSexp (const std::set< int > & v)\fC [inline]\fP"
.PP
Definition at line 62 of file RcppSexp.h.
.PP
References DEPRECATED().
.SS "RcppSexp::RcppSexp (const std::set< double > & v)\fC [inline]\fP"
.PP
Definition at line 63 of file RcppSexp.h.
.PP
References DEPRECATED().
.SS "RcppSexp::RcppSexp (const std::set< std::string > & v)\fC [inline]\fP"
.PP
Definition at line 64 of file RcppSexp.h.
.PP
References DEPRECATED().
.SS "RcppSexp::RcppSexp (const std::set< Rbyte > & v)\fC [inline]\fP"
.PP
Definition at line 65 of file RcppSexp.h.
.PP
References DEPRECATED().
.SH "Member Function Documentation"
.PP 
.SS "bool RcppSexp::asBool () const\fC [inline]\fP"
.PP
Definition at line 70 of file RcppSexp.h.
.SS "double RcppSexp::asDouble () const\fC [inline]\fP"
.PP
Definition at line 71 of file RcppSexp.h.
.SS "int RcppSexp::asInt () const\fC [inline]\fP"
.PP
Definition at line 72 of file RcppSexp.h.
.SS "Rbyte RcppSexp::asRaw () const\fC [inline]\fP"
.PP
Definition at line 73 of file RcppSexp.h.
.SS "SEXP RcppSexp::asSexp () const\fC [inline]\fP"explicit conversion to SEXP 
.PP
Definition at line 130 of file RcppSexp.h.
.SS "std::string RcppSexp::asStdString () const\fC [inline]\fP"
.PP
Definition at line 74 of file RcppSexp.h.
.SS "std::vector<bool> RcppSexp::asStdVectorBool () const\fC [inline]\fP"
.PP
Definition at line 79 of file RcppSexp.h.
.SS "std::vector<double> RcppSexp::asStdVectorDouble () const\fC [inline]\fP"
.PP
Definition at line 76 of file RcppSexp.h.
.SS "std::vector<int> RcppSexp::asStdVectorInt () const\fC [inline]\fP"
.PP
Definition at line 75 of file RcppSexp.h.
.SS "std::vector<Rbyte> RcppSexp::asStdVectorRaw () const\fC [inline]\fP"
.PP
Definition at line 78 of file RcppSexp.h.
.SS "std::vector<std::string> RcppSexp::asStdVectorString () const\fC [inline]\fP"
.PP
Definition at line 77 of file RcppSexp.h.
.SS "SEXP RcppSexp::attr (const std::string & name) const\fC [inline]\fP"extract the given attribute 
.PP
Definition at line 115 of file RcppSexp.h.
.SS "std::vector<std::string> RcppSexp::attributeNames () const\fC [inline]\fP"extracts the names of the attributes of the wrapped SEXP 
.PP
Definition at line 105 of file RcppSexp.h.
.SS "void RcppSexp::DEPRECATED ()\fC [inline, protected]\fP"
.PP
Definition at line 139 of file RcppSexp.h.
.PP
Referenced by RcppSexp().
.SS "bool RcppSexp::hasAttribute (const std::string & attr) const\fC [inline]\fP"Identifies if the SEXP has the given attribute 
.PP
Definition at line 110 of file RcppSexp.h.
.SS "bool RcppSexp::isNULL () const\fC [inline]\fP"is this object NULL 
.PP
Definition at line 120 of file RcppSexp.h.
.SS "RcppSexp::operator SEXP () const\fC [inline]\fP"implicit conversion to SEXP 
.PP
Definition at line 97 of file RcppSexp.h.
.SS "void RcppSexp::protect ()\fC [inline]\fP"Calls the preserve method of the wrapped RObject, which prevents the underlying SEXP from being garbage collected 
.PP
Definition at line 86 of file RcppSexp.h.
.SS "void RcppSexp::release ()\fC [inline]\fP"calls the release method of the RObject. the underlying SEXP becomes subject of garbage collection 
.PP
Definition at line 92 of file RcppSexp.h.
.SS "int RcppSexp::sexp_type () const\fC [inline]\fP"The SEXP typeof, calls TYPEOF on the underlying SEXP 
.PP
Definition at line 125 of file RcppSexp.h.
.SH "Member Data Documentation"
.PP 
.SS "Rcpp::RObject \fBRcppSexp::object\fP\fC [protected]\fP"The RObject this wraps 
.PP
Definition at line 137 of file RcppSexp.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Rcpp from the source code.
