.TH "src/RObject.cpp" 3 "2 Jan 2010" "Rcpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/RObject.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Rcpp/RObject.h>\fP
.br
\fC#include <algorithm>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBRcpp\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "RObject \fBRcpp::wrap\fP (SEXP m_sexp=R_NilValue)"
.br
.ti -1c
.RI "RObject \fBRcpp::wrap\fP (const bool &v)"
.br
.ti -1c
.RI "RObject \fBRcpp::wrap\fP (const double &v)"
.br
.ti -1c
.RI "RObject \fBRcpp::wrap\fP (const int &v)"
.br
.ti -1c
.RI "RObject \fBRcpp::wrap\fP (const Rbyte &v)"
.br
.ti -1c
.RI "RObject \fBRcpp::wrap\fP (const std::string &v)"
.br
.ti -1c
.RI "RObject \fBRcpp::wrap\fP (const std::vector< bool > &v)"
.br
.ti -1c
.RI "RObject \fBRcpp::wrap\fP (const std::vector< int > &v)"
.br
.ti -1c
.RI "RObject \fBRcpp::wrap\fP (const std::vector< double > &v)"
.br
.ti -1c
.RI "RObject \fBRcpp::wrap\fP (const std::vector< Rbyte > &v)"
.br
.ti -1c
.RI "RObject \fBRcpp::wrap\fP (const std::vector< std::string > &v)"
.br
.ti -1c
.RI "RObject \fBRcpp::wrap\fP (const std::set< int > &v)"
.br
.ti -1c
.RI "RObject \fBRcpp::wrap\fP (const std::set< double > &v)"
.br
.ti -1c
.RI "RObject \fBRcpp::wrap\fP (const std::set< Rbyte > &v)"
.br
.ti -1c
.RI "RObject \fBRcpp::wrap\fP (const std::set< std::string > &v)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Rcpp from the source code.
