# -*- tab-width: 8 -*- 
#
# Makefile for Rcpp 
#
# Copyright (C) 2008    Dirk Eddelbuettel <edd@debian.org>

## the 'package' library contains both Rcpp.{cpp,h} and the RcppExample used to demonstrate the package
## it is loaded via library(Rcpp) but is not used for compiling / linking against
PKGLIB 		= Rcpp$(DYLIB_EXT)
PKGOBJ 		= RcppExample.o Rcpp.o

## the 'user' library contains only Rcpp.{cpp,h} and is what users need for their projects
## we place it inside the inst/ directory so that it gets installed 
USERDIR		= ../inst/lib
USERLIB		= libRcpp$(DYLIB_EXT)
USEROBJ		= Rcpp.o

## more correct version of shared library build
#		= gcc -shared -Wl,-soname,librcpp.so.5 \
#                                -o ../librcpp.so.5.0 Rcpp.o
## where you'd still need the softlink from librcpp.so.5.0 to librcpp.so

all: 		$(PKGLIB) $(USERLIB) userLibrary

$(PKGLIB): 	$(PKGOBJ)
		$(SHLIB_CXXLD) -o $(PKGLIB) $^ $(SHLIB_CXXLDFLAGS) $(ALL_LIBS)

$(USERLIB):	$(USEROBJ)
		$(SHLIB_CXXLD) -o $(USERLIB) $^ $(SHLIB_CXXLDFLAGS) $(ALL_LIBS)

userLibrary: 	$(USERLIB)
		-@if test ! -e $(USERDIR)$(R_ARCH); then mkdir -p $(USERDIR)$(R_ARCH); fi
		cp $(USERLIB) $(USERDIR)$(R_ARCH)
		cp Rcpp.h $(USERDIR)

.PHONY: 	all clean userLibrary

clean:
		rm -r $(OBJECTS) $(SHLIBS) $(USERLIB) 
